on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          local-cache: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.0
      - uses: actions/cache/restore@v4
        id: cache-debug-build-android-restore
        with:
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
          key: cache-android-build
      - run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp
          haxelib install lime 8.1.1
          haxelib install openfl 9.2.2
          haxelib --never install flixel 5.2.2
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.10.0
          haxelib install away3d
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc
          haxelib install flxanimate 3.0.4
          haxelib git tjson https://github.com/JWambaugh/TJSON
          haxelib git hxjsonast https://github.com/nadako/hxjsonast/
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib install hscript
          haxelib install hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
      - run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - run: echo "${{github.run_id}}" > VERSION
      - run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
      - uses: actions/github-script@v7
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }
      - uses: actions/cache/save@v4
        id: cache-release-build-android-save
        with:
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/
          key: cache-android-build
      - uses: actions/upload-artifact@v4
        with:
          name: weekly-public
          path: export/release/android/bin/app/build/outputs/apk/debug
